### PR TITLE
[Feature] add method getIdentifier in  MixResource and change plugin'…

### PR DESCRIPTION
**Pull request by DaSheng1994**
…s appt2 package id , enable host to share resources with plugin

Signed-off-by: sheng <769273297@qq.com>

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/Shadow?pullRequest=493) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/Shadow?pullRequest=493) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/Shadow?pullRequest=493) it.</sub>

**Comment by shifujun** [comment]
@DaSheng1994 方便的话，请签署一下cla，这是腾讯开源项目统一的协议。
image

**Comment by DaSheng1994** [comment]
> @DaSheng1994 方便的话，请签署一下cla，这是腾讯开源项目统一的协议。
> image

谢谢作者的提醒，我已经签署完毕

**Comment by LinXueyuanStdio** [comment]
签了个寂寞

**Pull request closed without merging**
