### PR TITLE
支持一个Manager加载多个插件

### PR DESCRIPTION
**Pull request by PhantomQi**

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/Shadow?pullRequest=86) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/Shadow?pullRequest=86) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/Shadow?pullRequest=86) it.</sub>

**Comment by PhantomQi** [comment]
> 这只是sample的代码。虽说加了partKey可以支持返回不同的PPS，但是作为sample，还是没有演示如何使用多个PPS。

done

**Comment by PhantomQi** [comment]
@shifujun 抽空看下是否OK了？

**Comment by shifujun** [comment]
这个一直有文件冲突啊，怎么会在等我看呢？
image

**Comment by PhantomQi** [comment]
> 这个一直有文件冲突啊，怎么会在等我看呢？
> image

冲突已处理

**Pull request merged**
